### ISSUE TITLE
Break into Smaller Lessons possibly with basic labs

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/intro-to-ruby-iterators#11]
This README has a 35% drop-off. My suggestions of what to change revolve around breaking into 3 seperate readmes/lab pairings (6 pieces of content in general):
1. Looping with Blocks
   Focus entirely on the `do`, `end` syntax with `#times` and simple iterators. Explain the flow of the loop and how the block is being passed. That the block is what will get repeated X times.
2. Explain simple yield
   Focus on `do`, `end` with a simple yield, like `10.times{|i| puts i}` where we can explain what is being yielded to the block and the `| |` syntax.
3. Iteration with arrays
   Put it all together and show iterating over elements in an array.

We should also show them some patterns of not returning out of an iteration but using break instead. And how to setup state at first and then modify it in the block and return it as the method.

Inspiration and Additional Resources for Students and Curriculum Writers:

http://www.eriktrautman.com/posts/ruby-explained-iteration
https://www.codecademy.com/courses/ruby-beginner-en-XYcN1/0/1?curriculum_id=5059f8619189a5000201fbcb
http://code.tutsplus.com/tutorials/ruby-for-newbies-iterators-and-blocks--net-17089
http://rubylearning.com/satishtalim/ruby_blocks.html
http://ruby.bastardsbook.com/chapters/loops/

cc @AnnJohn @jmburges

**Comment by jongrover** [comment]
I agree with the suggestion to break this apart into at least 2 lessons. One that teaches loops first and lets students get confident working with `while` in a lab before introducing iterators like `each` as an alternative in a separate lesson. There could even be a lab that helps demonstrate when it is ideal to use an `each` iterator over a `while` loop.

My reasoning is that as I read through this lab and imagined myself being a beginner I felt overwhelmed by the amount of new information, i sensed I would like to play with loops for a while before learning that Ruby has additional methods like each that abstract away the incrementation.

**Comment by aviflombaum** [comment]
@jongrover loops are different than iteration as they do not accept blocks. We cover `while` and looping earlier and are not seeing a massive drop off on those topics.

![Track dropoff](https://dl.dropboxusercontent.com/s/r2ww5rn3hol4mzc/2015-12-01%20at%201.50%20PM.png)

It looks like while has drop-off too just not as significant.

![while](https://dl.dropboxusercontent.com/s/6ycnt0l0viv14c2/2015-12-01%20at%201.50%20PM%20%281%29.png)

**Comment by jongrover** [comment]
I see what you mean. Perhaps short quizzes or REPLs could help break up the reading and give the student some active time to help combat dropoff . Something I'm trying to do recently is have some activity for students at every 2 screen heights of reading max. This is just a guess though, asking the students who dropped off why, would be the best I suppose.

**Comment by aviflombaum** [comment]
Ya, I like Quizzes, I'm not a fan of our REPL implementation - I'd rather just give a very simple lab with the answer broken down in the README. Want to try to tackle breaking iteration and looping down again in the Intro to Ruby Development Track? Maybe work with @vicfriedman on it?

I think animations like the ones from Brett Victors [Learnable Programming](http://worrydream.com/LearnableProgramming/) would help too.

**Comment by AnnJohn** [comment]
A couple of other things with this lesson.

The first loop it mentions is the `times` loop but it's not covered in the looping unit so the student is automatically confused. 

The first section looping vs. iteration can also be too much. Why not start with just presenting the problem instead of talking about iteration in the third sentence of the readme. So start with a refresher on looping and use the example in the third code block. 

![screen shot 2015-12-01 at 5 38 13 pm](https://cloud.githubusercontent.com/assets/1892150/11516647/91110900-9852-11e5-8560-d6d20f510a99.png)

The first two (`times` loop and the one on outputting a phrase based on a certain input) are just not necessary. That shortens the intro, and doesn't mention iteration until the very end when we're about to dive in to `#each`

When you go into looping with `#each`, why not stick with the same example in the above screenshot instead of introducing something new? Gives a good sense of continuity. 

Also blocks are discussed, but a full discussion of blocks doesn't happen until a paragraph below. I think we try to explain the syntax and what's happening at the same time, when we should maybe focus first on syntax. But I think this is what you were trying to say already with breaking it up into three readmes.

**Comment by alexgriff** [comment]
The [About Iteration and Abstraction](https://github.com/learn-co-curriculum/iterators-and-abstraction-ruby) readme seems to cover the material in the first section of this readme about looping vs. iteration.

I would suggest an additional readme all about #each that could break down each element of a standard #each iteration--blocks, yielding, the pipes-- using much of the material here.  

Perhaps the discussion of return values could be moved to the next lab [Squaring an Array](https://github.com/learn-co-curriculum/square_array) so there is less information being heaped upon the student at once.  In that lab it will become very apparent that the return value of #each is affecting the outcome.  The student could discover what that means for themselves with some mention of what to look out for in the lab's readme.

**Comment by sgharms** [comment]
This is a very good discussion and has lots of great data in it. Judging by the issues in this topic, we need to apply a larger-context edit. I'm putting it as an item in the Curriculum icebox and closing it here. In the icebox we can see it and plan it.
