### ISSUE TITLE
highlighting

### ISSUE THREAD

**Issue by zokratez** [learn-co-curriculum/intro-to-ruby-iterators#16]
perhaps if we could have a highlighter on our lessons as we go along so we may go back to the lesson and kind of bookmark it with our own color highlights.
Also if there ws an option to print  whole lesson so we may copy it and read it in the train while we dont have any wifi.
But its all good, I can sacrifice Ha!
thanks

**Comment by AnnJohn** [comment]
these are great suggestions @zokratez. We've worked internally on annotating and note taking tools but they're not yet ready and might not be for a while since we have other features that we're rolling out. 

With lessons, I don't think we'll introduce an option to print them. but we will be looking more into mobile apps for Learn so that it can be used, for example, on the train (though of course you may only be able to have one lesson available at a time if there is no wifi). Thanks again!
