### ISSUE TITLE
this needs to provide an example stating a return is required for iterator methods

### ISSUE THREAD

**Issue by melzreal** [learn-co-curriculum/intro-to-ruby-iterators#26]
Its the first time we are required to actually return something from a ruby method on the next lab, since all the other methods written for the ruby labs up until this point had implicit returnsThere should be an actual method example stating a return is necessary after using iterators since that was the only way to get the code to pass - unless there was an alternative way?

**Comment by Sdcrouse** [comment]
Hi! First of all, I'm a student like yourself, just to prevent any misunderstandings. You are right in saying that Ruby methods have implicit returns; a method's return value is the value of its last line of code (unless you specifically say "return this_value", of course). 

For example, if a puts statement is the last line of code in a method, then the method returns nil as its value since the return value of puts is nil. And if you write "variable = 3" (minus the quotes), then 3 is the return value.

Bearing that in mind, that's the reason why the Square Array Lab asks you about the return value of calling #each on an array. Also, you don't need an explicit "return" statement to complete this lab.

I hope this helps, even though it's been four months since you raised this issue :)

---Sdcrouse
